### ISSUE TITLE
Tabbed reporting display demo

### ISSUE THREAD

**Issue by dmenne** [mmparker/tabbed_reporting#1]
Is this what you intended (Firefox and Chrome, recent versions, Windows)?

![2016-01-01 12_07_20-tabbed_reporting_report_with_jquery rmd at master mmparker_tabbed_reporting](https://cloud.githubusercontent.com/assets/506275/12070610/4a351c42-b080-11e5-81b0-506a9729d615.png)

**Comment by mmparker** [comment]
Hmm - definitely not. It should look like this (for the tabbed version):

![image of correctly-rendered tabbed report](http://revolution-computing.typepad.com/.a/6a010534b1db25970b01bb08a47459970d-800wi)

Sorry for the trouble. Can you give me more details about how you got to that point?

**Comment by dmenne** [comment]
Simply following the link on the github page you provided. Some language problems? Currently, the link is dead, but if you should have problems, I could download the whole stuff and check locally.

**Comment by mmparker** [comment]
Ah, GitHub has trouble rendering R-Markdown source files, so its previews always look strange. I find it easiest to click the "Raw" button and view the plaintext versions of the source files:
- [Simple report (raw)](https://raw.githubusercontent.com/mmparker/tabbed_reporting/master/report.rmd)
- [Tabbed report (raw)](https://raw.githubusercontent.com/mmparker/tabbed_reporting/master/report_with_jquery.rmd)

The rendered HTML reports aren't in the GitHub repository at all, but are hosted on the blog site:
- [Simple report (rendered)](http://blog.revolutionanalytics.com/downloads/report.html)
- [Tabbed report (rendered)](http://blog.revolutionanalytics.com/downloads/report_with_jquery.html)

These links are live as I post them, but please let me know if you have any trouble, or if this doesn't resolve the issue for you. I can always try adding the rendered HTML to this repository, too - that might be the most robust approach.

**Comment by dmenne** [comment]
Thanks, Everything fine. Maybe add  a comment on the subject.
